name: Build-APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check-out code
      uses: actions/checkout@v4

    # Set up JDK 17 (required by AGP 8.x)
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # Cache Gradle deps to speed up subsequent builds
    - name: Gradle cache
      uses: gradle/gradle-build-action@v3

    # Build debug APK (includes native .so)
    - name: Assemble Debug
      run: ./gradlew assembleDebug

    # Upload the generated APK so you can download it
    - name: Publish APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: CustomAUXViewer-debug
        path: app/build/outputs/apk/debug/app-debug.apk
